baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "DELPHI"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "solid/circle-info"
    url = "/about"
    weight = 1

# About
[[menu.main]]
    parent = "about"
    name = "About Delphi"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Delphi Milestones"
    url = "/about/milestones"
    weight = 2
[[menu.main]]
    parent = "about"
    name = "Our Team"
    url = "/about/team"
    weight = 3
[[menu.main]]
    parent = "about"
    name = "Center of Excellence"
    url = "/about/center-of-excellence"
    weight = 4
[[menu.main]]
    parent = "about"
    name = "Research"
    url = "/about/publications"
    weight = 5
[[menu.main]]
    parent = "about"
    name = "Blog"
    url = "/blog"
    weight = 6
[[menu.main]]
    parent = "about"
    name = "News"
    url = "/about/news"
    weight = 7
[[menu.main]]
    parent = "about"
    name = "Careers"
    url = "/about/careers"
    weight = 8
[[menu.main]]
    parent = "about"
    name = "Contact Us"
    url = "https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform"
    weight = 9

# covid19
[[menu.main]]
    identifier = "covid19"
    name = "COVID-19"
    pre = "solid/virus"
    url = "/covid19/"
    weight = 2
[[menu.main]]
    parent = "covid19"
    name = "About COVIDcast"
    url = "/covid19/"
    weight = 1
[[menu.main]]
    identifier = "covid19-covidcast"
    parent = "covid19"
    name = "Delphi Epidata Dashboard"
    url = "/covidcast/"
    weight = 20
[[menu.main]]
    parent = "covid19"
    name = "CTIS Dashboard"
    url = "/covidcast/survey-results"
    weight = 30
[[menu.main]]
    parent = "covid19"
    name = "Export Data"
    url = "/covidcast/export"
    weight = 40
[[menu.main]]
    parent = "covid19"
    name = "Terms Of Use"
    url = "/covid19/terms-of-use"
    weight = 50

# flu
[[menu.main]]
    identifier = "flu"
    name = "Flu & Other Pathogens"
    pre = "solid/disease"
    url = "/flu/"
    weight = 3

# tools
[[menu.main]]
    identifier = "tools"
    name = "Tools"
    pre = "solid/screwdriver-wrench"
    url = "/tools/"
    weight = 5
[[menu.main]]
    parent = "tools"
    name = "Tools Overview"
    url = "/tools/"
    weight = 1
# utils
[[menu.main]]
    parent = "tools"
    identifier = "utils"
    name = "Dashboards"
    url = "/tools/#dashboards"
    weight = 9
[[menu.main]]
    parent = "utils"
    name = "Delphi Epidata Dashboard"
    url = "/covidcast/"
    weight = 10
[[menu.main]]
    parent = "utils"
    name = "Indicator Status"
    url = "/covidcast/indicator-status"
    weight = 20
[[menu.main]]
    parent = "utils"
    name = "Dashboard Builder"
    url = "/covidcast/dashboard"
    weight = 30
[[menu.main]]
    parent = "utils"
    name = "Forecast Evaluation"
    url = "/forecast-eval/"
    weight = 40
[[menu.main]]
    parent = "utils"
    name = "Epi Signal Visualization"
    url = "/epivis/"
    weight = 50
[[menu.main]]
    parent = "tools"
    name = "Archived"
    url = "/tools/#archived"
    weight = 80

[[menu.main]]
    parent = "tools"
    identifier = "forecasting"
    name = "Forecasting"
    url = "/tools/#forecasting"
    weight = 50

[[menu.main]]
    parent = "forecasting"
    name = "COVID Forecasting"
    url = "https://covid19forecasthub.org/"
    weight = 1
[[menu.main]]
    parent = "forecasting"
    name = "Flu Forecasting"
    url = "https://www.cdc.gov/flu/weekly/flusight/index.html"
    weight = 2

[[menu.main]]
    identier = "Code"
    pre = "solid/code"
    name = "Code"
    url = "code"
    weight = 90
[[menu.main]]
    parent = "Code"
    name = "Code Overview"
    url = "code"
    weight = 1
[[menu.main]]
    parent = "Code"
    identifier = "APIClients"
    name = "API and Clients"
    url = "/code/#api-and-clients"
    weight = 2
[[menu.main]]
    parent = "APIClients"
    name = "Epidata"
    url = "https://github.com/cmu-delphi/delphi-epidata"
    weight = 7
[[menu.main]]
    parent = "APIClients"
    name = "Epidatr"
    url = "https://cmu-delphi.github.io/epidatr/"
    weight = 8
[[menu.main]]
    parent = "APIClients"
    name = "Epidatpy"
    url = "https://github.com/cmu-delphi/epidatpy"
    weight = 9

[[menu.main]]
    parent = "Code"
    identifier = "forecastingCode"
    name = "Forecasting"
    url = "code#forecasting"
    weight = 10
[[menu.main]]
    parent = "forecastingCode"
    name = "Forecasting Manual"
    weight = 1
[[menu.main]]
    parent = "forecastingCode"
    name = "Epiprocess"
    url = "https://cmu-delphi.github.io/epiprocess/"
    weight = 7
[[menu.main]]
    parent = "forecastingCode"
    name = "Epipredict"
    url = "https://cmu-delphi.github.io/epipredict/"
    weight = 7
[[menu.main]]
    parent = "Code"
    name = "Github"
    pre = "brands/github"
    url = "https://github.com/cmu-delphi/"
    weight = 70

[[menu.main]]
    identifier = "api"
    name = "Epidata API"
    pre = "solid/database"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 100

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    mission = "To develop the theory and practice of epidemic detection, tracking and forecasting, and their use in decision making, both public and private.  Our vision is to make this technology as useful as weather forecasting is today."
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata"
    toolUrl = "/tools/"
    twitter = "CmuDelphi"
    contactForm = "https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform"
    feedbackForm = "https://docs.google.com/forms/d/e/1FAIpQLSeIeOJtrAhdOriEyiRY7LkpQX8DZBY19dl6De8l56Q9CZhmxw/viewform?usp=pp_url&entry.1245962748="
    feedbackLikelihoodMobile = 0.2
    feedbackLikelihoodDesktop = 1
    feedbackDelayMin = 45  # in sec
    feedbackDelayMax = 180 # in sec
    feedbackDuration = 60  # show it for 60sec
    highlightLinks = ""
