baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "DELPHI"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "solid/info-circle"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Delphi Research Group"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Team"
    url = "/about/team"
    weight = 2
[[menu.main]]
    parent = "about"
    name = "Center of Excellence"
    url = "/about/center-of-excellence"
    weight = 3
[[menu.main]]
    parent = "about"
    name = "Publications"
    url = "/about/publications"
    weight = 4
[[menu.main]]
    parent = "about"
    name = "News"
    url = "/about/news"
    weight = 4
[[menu.main]]
    identifier = "covidcast"
    name = "COVIDcast"
    pre = "solid/map"
    url = "/covidcast/"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "COVIDcast Overview"
    url = "/covidcast/"
    weight = 1
[[menu.main]]
    parent = "covidcast"
    name = "Explore a Location"
    url = "/covidcast/summary"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "Explore an Indicator"
    url = "/covidcast/indicator"
    weight = 3
[[menu.main]]
    parent = "covidcast"
    name = "Explore Correlations"
    url = "/covidcast/correlation"
    weight = 4
[[menu.main]]
    parent = "covidcast"
    name = "Dashboard Builder"
    url = "/covidcast/dashboard"
    weight = 20
[[menu.main]]
    parent = "covidcast"
    name = "Classic Map"
    url = "/covidcast/classic"
    weight = 30
[[menu.main]]
    parent = "covidcast"
    name = "Forecast Evaluation"
    url = "/forecast-eval/"
    weight = 40
[[menu.main]]
    parent = "covidcast"
    name = "Surveys"
    url = "/covidcast/surveys"
    weight = 50
[[menu.main]]
    parent = "covidcast"
    name = "Survey Results"
    url = "/covidcast/survey-results"
    weight = 51
[[menu.main]]
    parent = "covidcast"
    name = "Indicator Status Overview"
    url = "/covidcast/indicator-status"
    weight = 60
[[menu.main]]
    parent = "covidcast"
    name = "Export Data"
    url = "/covidcast/export"
    weight = 70
[[menu.main]]
    parent = "covidcast"
    name = "Data Anomalies"
    url = "/covidcast/data-anomalies"
    weight = 71
[[menu.main]]
    parent = "covidcast"
    name = "Release Log"
    url = "/covidcast/release-log"
    weight = 80
[[menu.main]]
    parent = "covidcast"
    name = "Terms Of Use"
    url = "/covidcast/terms-of-use"
    weight = 90
[[menu.main]]
    identifier = "flu"
    name = "Flu and Other Diseases"
    pre = "solid/virus"
    url = "/flu"
    weight = 3
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "solid/book"
    url = "/blog"
    weight = 4
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "brands/github"
    url = "https://github.com/cmu-delphi/"
    weight = 5
[[menu.main]]
    identifier = "api"
    name = "API"
    pre = "solid/database"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 6

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    mission = "Develop the theory and practice of epidemiological forecasting, with a long-term vision of making this technology as universally accepted and useful as weather forecasting is today."
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata"
    twitter = "CmuDelphi"
    contactForm = "https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform"
    feedbackForm = "https://docs.google.com/forms/d/e/1FAIpQLSeIeOJtrAhdOriEyiRY7LkpQX8DZBY19dl6De8l56Q9CZhmxw/viewform?usp=pp_url&entry.1245962748="
    feedbackLikelihoodMobile = 0.2
    feedbackLikelihoodDesktop = 1
    feedbackDelayMin = 45  # in sec
    feedbackDelayMax = 180 # in sec
    feedbackDuration = 60  # show it for 60sec
    highlightLinks = "/covidcast/dashboard"
