baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "DELPHI"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "solid/circle-info"
    url = "/about"
    weight = 1

# About
[[menu.main]]
    parent = "about"
    name = "About Delphi"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Our Team"
    url = "/about/team"
    weight = 2
[[menu.main]]
    parent = "about"
    name = "Center of Excellence"
    url = "/about/center-of-excellence"
    weight = 3
[[menu.main]]
    parent = "about"
    name = "Research"
    url = "/about/publications"
    weight = 4
[[menu.main]]
    parent = "about"
    name = "Blog"
    url = "/blog"
    weight = 5
[[menu.main]]
    parent = "about"
    name = "News"
    url = "/about/news"
    weight = 6
[[menu.main]]
    parent = "about"
    name = "Careers"
    url = "/about/careers"
    weight = 7

# covid19
[[menu.main]]
    identifier = "covid19"
    name = "COVID-19"
    pre = "solid/virus"
    url = "/covid19/"
    weight = 2
[[menu.main]]
    parent = "covid19"
    name = "About COVIDcast"
    url = "/covid19/"
    weight = 1
[[menu.main]]
    parent = "covid19"
    name = "About CTIS"
    url = "/covid19/ctis"
    weight = 10
[[menu.main]]
    identifier = "covid19-covidcast"
    parent = "covid19"
    name = "COVIDcast Dashboard"
    url = "/covidcast/"
    weight = 20
[[menu.main]]
    parent = "covid19"
    name = "CTIS Dashboard"
    url = "/covidcast/survey-results"
    weight = 30
[[menu.main]]
    parent = "covid19"
    name = "Export Data"
    url = "/covidcast/export"
    weight = 40
[[menu.main]]
    parent = "covid19"
    name = "Terms Of Use"
    url = "/covid19/terms-of-use"
    weight = 50

# flu
[[menu.main]]
    identifier = "flu"
    name = "Flu & Other Pathogens"
    pre = "solid/disease"
    url = "/flu/"
    weight = 3

# tools
[[menu.main]]
    identifier = "tools"
    name = "Tools"
    pre = "solid/screwdriver-wrench"
    url = "/tools/"
    weight = 5
[[menu.main]]
    parent = "tools"
    name = "Tools Overview"
    url = "/tools/"
    weight = 1
[[menu.main]]
    parent = "tools"
    name = "COVIDcast Dashboard"
    url = "/covidcast/"
    weight = 10
[[menu.main]]
    parent = "tools"
    name = "COVIDcast R Package"
    url = "https://cmu-delphi.github.io/covidcast/covidcastR/"
    weight = 11
[[menu.main]]
    parent = "tools"
    name = "COVIDcast Python Package"
    url = "https://cmu-delphi.github.io/covidcast/covidcast-py/html/"
    weight = 12
[[menu.main]]
    parent = "tools"
    name = "Indicator Status"
    url = "/covidcast/indicator-status"
    weight = 20
[[menu.main]]
    parent = "tools"
    name = "Dashboard Builder"
    url = "/covidcast/dashboard"
    weight = 30
[[menu.main]]
    parent = "tools"
    name = "Forecast Evaluation"
    url = "/forecast-eval/"
    weight = 40
[[menu.main]]
    parent = "tools"
    name = "EpiVis"
    url = "/epivis/"
    weight = 50
[[menu.main]]
    parent = "tools"
    name = "Archived Tools"
    url = "/tools/archive/"
    weight = 80


[[menu.main]]
    identier = "github"
    pre = "brands/github"
    name = "GitHub"
    url = "https://github.com/cmu-delphi/"
    weight = 90


[[menu.main]]
    identifier = "api"
    name = "API"
    pre = "solid/database"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 100

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    mission = "Develop the theory and practice of epidemiological forecasting, with a long-term vision of making this technology as universally accepted and useful as weather forecasting is today."
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata"
    twitter = "CmuDelphi"
    contactForm = "https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform"
    feedbackForm = "https://docs.google.com/forms/d/e/1FAIpQLSeIeOJtrAhdOriEyiRY7LkpQX8DZBY19dl6De8l56Q9CZhmxw/viewform?usp=pp_url&entry.1245962748="
    feedbackLikelihoodMobile = 0.2
    feedbackLikelihoodDesktop = 1
    feedbackDelayMin = 45  # in sec
    feedbackDelayMax = 180 # in sec
    feedbackDuration = 60  # show it for 60sec
    highlightLinks = ""
