baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "DELPHI"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "solid/info-circle"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Delphi Research Group"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Team"
    url = "/about/team"
    weight = 2
[[menu.main]]
    parent = "about"
    name = "Publications"
    url = "/about/publications"
    weight = 3
[[menu.main]]
    identifier = "covidcast"
    name = "COVIDcast"
    pre = "solid/map"
    url = "/covidcast"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "Map Overview"
    url = "/covidcast"
    weight = 1
[[menu.main]]
    parent = "covidcast"
    name = "Timelapse"
    url = "/covidcast/timelapse"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "Top 10"
    url = "/covidcast/top10"
    weight = 3
[[menu.main]]
    parent = "covidcast"
    name = "Single Region"
    url = "/covidcast/single"
    weight = 4
[[menu.main]]
    parent = "covidcast"
    name = "Surveys"
    url = "/covidcast/surveys"
    weight = 5
[[menu.main]]
    parent = "covidcast"
    name = "Survey Results"
    url = "/covidcast/survey-results"
    weight = 6
[[menu.main]]
    parent = "covidcast"
    name = "Export Data"
    url = "/covidcast/export"
    weight = 7
[[menu.main]]
    parent = "covidcast"
    name = "Release Log"
    url = "/covidcast/release-log"
    weight = 8
[[menu.main]]
    parent = "covidcast"
    name = "Terms Of Use"
    url = "/covidcast/terms-of-use"
    weight = 9
[[menu.main]]
    identifier = "flu"
    name = "Flu and Other Diseases"
    pre = "solid/virus"
    url = "/flu"
    weight = 3
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "solid/book"
    url = "/blog"
    weight = 4
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "brands/github"
    url = "https://github.com/cmu-delphi/"
    weight = 5
[[menu.main]]
    identifier = "api"
    name = "API"
    pre = "solid/database"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 6

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    mission = "Develop the theory and practice of epidemiological forecasting, with a long-term vision of making this technology as universally accepted and useful as weather forecasting is today."
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata"
    twitter = "CmuDelphi"
    feedbackForm = "https://docs.google.com/forms/d/e/1FAIpQLSffGhrCsZmDSF4Lbeg9lB-Gp_Uf7z7D9ust-vXk1F5V1SElig/viewform?usp=pp_url&entry.1245962748="
    feedbackRequest = "Please provide feedback"
    feedbackDelay = 6 # wait for initial 60sec to show the notification
    feedbackDuration = 60 # show it for 60sec
    feedbackInterval = 120 # wait for another 120sec to show another