name: www-main
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - python=3.9.1
  - pip
  - r-base
  - glib
  - mscorefonts
  - r-cairo
  - r-devtools
  - r-directlabels
  - r-gridextra
  - r-reticulate
  - r-blogdown
  - r-svglite
  - r-dplyr
  - r-ggplot2
  - r-jsonlite
  - r-httr
  - r-codetools
  - r-maptools
  - r-purrr
  - r-rlang
  - r-tidyr
  - r-vctrs
  - r-farver
  - r-vctrs
  - r-testthat
  - r-isoband
  - r-ggrepel
  - r-plotly
  - r-sf
  - r-lubridate
  - r-plyr
  - r-ggpubr
  - r-stringi
  - r-fansi
  - r-openssl
  - r-mime
  - r-cli
  - r-rcpp
  - r-tidyverse
  - r-bit
  - r-tzdb
  - r-triebeard
  - r-digest
  - r-vroom
  - r-urltools
  - r-base64url
  - r-readr >=2
  - pandoc
  - fiona
  - geopandas
  - pandas
  - numpy
  - pillow
  - pyproj
  - matplotlib
  - udunits2
  - pip:
      - covidcast==0.1.3
